spring.application.name=checkProfile_backend
# Progresql
spring.datasource.url=jdbc:postgresql://localhost:5432/checkprofil
spring.datasource.username=devdouanla
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.baselineOnMigrate=true
spring.flyway.baselineVersion=0
